apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress/ingress.yaml
# 운영에서만 덮어쓸 패치들(선택)
#patches:
#  - path: patches/replicas.yaml
images:
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/auth-service
    newTag: 419d41e0f983
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
    newTag: 43475943b19c
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/book-service
    newTag: e2f88967620c
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/gateway-service
    newTag: 419d41e0f983
