apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secrets/sealed-aws-secrets.yaml
  - ingress/ingress.yaml
  - maintenance/ecr-creds-refresh.yaml
# 운영에서만 덮어쓸 패치들(선택)
#patches:
#  - path: patches/replicas.yaml
images:
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/auth-service
    newTag: 02af0bff6c6c
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
    newTag: a7aab7c31d55
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/book-service
    newTag: 94ead19f63c4
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/gateway-service
    newTag: 02af0bff6c6c
