apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secrets/sealed-aws-secrets.yaml
  - ingress/ingress.yaml
  - maintenance/ecr-creds-refresh.yaml
# 운영에서만 덮어쓸 패치들(선택)
#patches:
#  - path: patches/replicas.yaml
images:
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/auth-service
    newTag: 1e173c7eb7e4
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
    newTag: c2ae7a1d1578
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/book-service
    newTag: e2f88967620c
  - name: 590183877725.dkr.ecr.ap-northeast-2.amazonaws.com/gateway-service
    newTag: 052fe768cb34
