{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "aws-credentials",
    "namespace": "listik-prod",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "aws-credentials",
        "namespace": "listik-prod",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "credentials": "AgBigP3lq3BxAw5UeVadpDcnSD3DGiqFdARSqq9Z3h/gPDmVbp2iR0bOSSQqHxWzxdSLWd/UJ+hFTyJJpAhs/Q8vhcLU3tz+XYWmyVFXaiYHXDYVRzhmsjk7wl67UtFMgH5VnT77eu7lmzcKk8D+0DqAJ92+PP/zD4Sv1uoc74FiRhysqQ8VAM1jRizXsjz8RqahZ2rJjVGwAdeKs5mjsp0DaXLRMtkLEYivFKdrd+FKspcVux9w5d9sfhGDd/WREVATUms5AhYIOC5IUb8NjmQH/eSobWjOQkqtQDwnzDV3DtMid1rvrXyDPXuXnbbyM0Qf4ZeTXBNvB8VeKXBl9BWjLfJZIoyP4Da9nlO8Q3mFcCwNSf9eggMLoWHmPI8q5IOhMWvUWqCobH3+MtVjoFunIroywzFiMCBQjjX4v27aIPY7J2iUFFioAZozDAA69UX3GBC2CxuCuqviGIBXxA68744ZIcisSf4HbUZMsJdqXC8rCgPiauVfl12omU9tw6WF5gF/oKFh0fn8XlQ7bsEz7lBGmsaWFmLl5LyVRJpZluYOfCjgLqeE/jlJJ3OydpjPqeClvqGchUpWlseECRW/HBO0JJKozKPCPsNP93df1Xklrh6gxt0VerZyX1WqMXqqCCSifw3Npyr1zztMU9tbZAuI9RssWbVEccEbHu1MVRd215N8lYHTkQzqoxeRkdXTMoGCHqdRjP404JUeXs+7pH4KOyewy1sMo/TK8JfxwIy/Y5C6AzdxRf1uxxTKDzosqSGBpoPZmjZVRywFZDW8FS0FLX749O5HFCa5zdF86uH27Rd+SOwVjWK+Q+yul+tcqTp9oZVajDZ+TySY04i1mgw0tw=="
    }
  }
}
